apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: docker-registry-credentials
  namespace: wordscapes-solver-front-end
data:
  .dockerconfigjson: {{ ghcr_credentials }}