- name: Fetch git information
  import_tasks: tasks/git-info.yml

- name: Build Docker image
  when: not publish
  shell: |
    docker build \
      -f ../Dockerfile \
      -t ghcr.io/ruchira088/wordscapes-solver-front-end:{{ git_branch }} \
      -t ghcr.io/ruchira088/wordscapes-solver-front-end:{{ git_branch }}-{{ git_commit }} \
      .../

- name: Build and publish Docker image
  when: publish
  block:
      - name: Login to GitHub container registry
        command: docker login ghcr.io -u USERNAME -p {{ access_token }}
        vars:
          access_token: "{{ lookup('aws_ssm', '/github/packages/read-write-token', region='ap-southeast-2') }}"

      - name: Publish Docker image
        shell: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            -t ghcr.io/ruchira088/wordscapes-solver-front-end:{{ git_branch }} \
            -t ghcr.io/ruchira088/wordscapes-solver-front-end:{{ git_branch }}-{{ git_commit }} \
            -f ../Dockerfile \
            ../