---
- hosts: localhost
  connection: local

  tasks:
    - name: Install dependencies
      import_tasks: tasks/install-dependencies.yml

    - name: Fetch git information
      import_tasks: tasks/git-info.yml

    - name: Create K8s resource files
      import_tasks: tasks/k8s-resource-files.yml
      vars:
        ghcr_credentials: "{{ lookup('aws_ssm', '/github/ghcr/docker-config', region='ap-southeast-2') }}"

    - name: Create kubeconfig
      import_tasks: tasks/k8s-config.yml

    - name: Deploy to K8s
      block:
        - name: Create Namespace
          command: kubectl apply -f k8s-output/Namespace.yaml --kubeconfig {{ kube_config }}

        - name: Create Docker registry secret
          command: kubectl apply -f k8s-output/DockerRegistryCredentials.yaml --kubeconfig {{ kube_config }}

        - name: Deploy application
          command: kubectl apply -f k8s-output --kubeconfig {{ kube_config }}

        - name: Wait for successful deployment
          command: kubectl rollout status deployment front-end-deployment --kubeconfig {{ kube_config }} -n wordscapes-solver-front-end

    - name: Delete output directory
      file:
        path: k8s-output
        state: absent
